apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-backend
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django-backend
  template:
    metadata:
      labels:
        app: django-backend
    spec:
      containers:
        - name: django
          image: kubermanagement-api:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8000
          env:
            - name: FIELD_ENCRYPTION_KEY
              valueFrom:
                secretKeyRef:
                  name: django-secrets
                  key: FIELD_ENCRYPTION_KEY
            - name: DJANGO_ALLOWED_HOSTS
              value: "*"
---
apiVersion: v1
kind: Service
metadata:
  name: django-backend
  namespace: default
spec:
  selector:
    app: django-backend
  ports:
    - name: http
      port: 8000
      targetPort: 8000
  type: ClusterIP
