# Generated by Django 5.0.14 on 2026-08-19 03:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('namespaces', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.CharField(max_length=500)),
                ('replicas', models.PositiveIntegerField(default=1)),
                ('cpu_request', models.CharField(default='100m', max_length=20)),
                ('cpu_limit', models.CharField(default='500m', max_length=20)),
                ('memory_request', models.CharField(default='128Mi', max_length=20)),
                ('memory_limit', models.CharField(default='512Mi', max_length=20)),
                ('status', models.CharField(choices=[('creating', 'Creating'), ('active', 'Active'), ('updating', 'Updating'), ('deleting', 'Deleting'), ('failed', 'Failed')], default='creating', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('namespace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apps', to='namespaces.namespace')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='application',
            constraint=models.UniqueConstraint(fields=('namespace', 'name'), name='unique_app_per_namespace'),
        ),
    ]
